language: csharp
sudo: required
mono: none
dotnet: 2.0.0
script:
  - cd ./src/
  - dotnet restore
  - dotnet build
  - dotnet test SpiceSharpParser.Tests/SpiceSharpParser.Tests.csproj
  - dotnet test SpiceSharpParser.IntegrationTests/SpiceSharpParser.IntegrationTests.csproj
